name: Publish OpenArabic

on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ—  Setup repo
        uses: actions/checkout@v3

      - name: ğŸ—  Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          check-latest: true
          cache: yarn
          cache-dependency-path: mobile/yarn.lock

      - name: ğŸ—  Setup Expo
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      
      - name: ğŸ—  Set publish URL
        working-directory: ./mobile
        run: cp ./constants/urls.publish.js ./constants/urls.js

      - name: ğŸ“¦  Install dependencies
        working-directory: ./mobile
        run: yarn install

      - name: ğŸš€  Publish app
        working-directory: ./mobile
        run: expo publish --non-interactive
