name: Run Jest Tests
on:
  push:
    branches-ignore: [main]
jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:5-focal
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: ${{ secrets.MONGO_MOCK_PASSWORD }}
          MONGO_INITDB_DATABASE: openarabic

    steps:
      - uses: actions/checkout@v2.4.2

      - name: üèó  Initialize MongoDB
        run: |
          mongosh --host localhost --port 27017 --username root --password ${{ secrets.MONGO_MOCK_PASSWORD }} --authenticationDatabase "admin" --file ./database/init-database-and-user.js

      - name: üèó  Setup Node.js
        uses: actions/setup-node@v3.3.0
        with:
          node-version: "16"
          check-latest: true

      - name: üß™  Test API
        working-directory: ./api
        env:
          PORT: 3030
          API_MONGO_DB_URL: mongodb://user:password@localhost:27017/openarabic
          API_TASHKEEL_URL: http://localhost:3020
        run: |
          yarn install
          yarn test

      - name: üß™  Test mobile
        working-directory: ./mobile
        run: |
          yarn install
          yarn test

      - name: üß™  Test Web
        working-directory: ./web
        run: |
          yarn install
          yarn test

      - name: ‚úÖ  Tests
        if: ${{ success() }}
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "context": "tests",
            "state": "success",
            "description": "Tests passed",
            "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          }'

      - name: üö®  Tests
        if: ${{ failure() }}
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "context": "tests",
            "state": "failure",
            "description": "Tests failed",
            "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          }'
