name: Run Jest Tests
on:
  push:
    branches-ignore: [main]
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.4.2

      - name: ğŸ— Start MongoDB
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: "5.0"
          mongodb-username: openarabic
          mongodb-password: ${{ secrets.MONGO_MOCK_PASSWORD }}
          mongodb-db: openarabic

      - name: ğŸ— Setup Node.js
        uses: actions/setup-node@v3.3.0
        with:
          node-version: "16"
          check-latest: true

      - name: ğŸ§ª Test API
        working-directory: ./api
        env:
          PORT: 3030
          API_MONGO_DB_URL: mongodb://openarabic:${{ secrets.MONGO_MOCK_PASSWORD }}@localhost:27017
          API_TASHKEEL_URL: http://localhost:3020
        run: |
          echo $API_MONGO_DB_URL
          yarn install
          yarn test

      - name: ğŸ§ª Test mobile
        working-directory: ./mobile
        run: |
          yarn install
          yarn test

      - name: ğŸ§ª Test Web
        working-directory: ./web
        run: |
          yarn install
          yarn test

      - name: âœ… Tests
        if: ${{ success() }}
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "context": "tests",
            "state": "success",
            "description": "Tests passed",
            "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          }'

      - name: ğŸš¨ Tests
        if: ${{ failure() }}
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "context": "tests",
            "state": "failure",
            "description": "Tests failed",
            "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          }'
