name: Build, Push and Deploy OpenArabic

on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ—  Prepare
        id: prep
        run: |
          branch=${GITHUB_REF##*/}
          sha=${GITHUB_SHA::8}
          ts=$(date +%s)
          echo "::set-output name=BUILD_ID::${branch}-${sha}-${ts}"

      - name: ğŸ—  Checkout
        uses: actions/checkout@v2.4.2

      - name: ğŸ—  Set up QEMU
        uses: docker/setup-qemu-action@v2.0.0

      - name: ğŸ—  Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.0.0

      - name: ğŸ—  Docker Login
        uses: docker/login-action@v2.0.0
        with:
          registry: registry.digitalocean.com/openarabic/
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: ğŸ—  Install Helm
        uses: Azure/setup-helm@v1
        with:
          version: ${{ env.HELM_VERSION_TO_INSTALL }}
        env:
          HELM_VERSION_TO_INSTALL: 3.9.0

      - name: ğŸ—  Login to registry using Helm
        run: |
          helm registry login registry.digitalocean.com/openarabic --username ${{ secrets.DOCKERHUB_USERNAME }} --password ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: ğŸ“¦  Build and Push Static to Container Registry
        uses: docker/build-push-action@v3.0.0
        with:
          file: ./static/Dockerfile
          tags: registry.digitalocean.com/openarabic/static:${{ steps.prep.outputs.BUILD_ID }}
          context: ./static
          push: true

      - name: ğŸ“¦  Build and Push API to Container Registry
        uses: docker/build-push-action@v3.0.0
        with:
          file: ./api/Dockerfile
          tags: registry.digitalocean.com/openarabic/api:${{ steps.prep.outputs.BUILD_ID }}
          context: ./api
          push: true

      - name: ğŸ“¦  Build and Push Tashkeel to Container Registry
        uses: docker/build-push-action@v3.0.0
        with:
          file: ./services/tashkeel/Dockerfile
          tags: registry.digitalocean.com/openarabic/tashkeel:${{ steps.prep.outputs.BUILD_ID }}
          context: ./services/tashkeel/
          push: true

      - name: ğŸ“¦  Build and Push Web to Container Registry
        uses: docker/build-push-action@v3.0.0
        with:
          file: ./web/Dockerfile
          tags: registry.digitalocean.com/openarabic/web:${{ steps.prep.outputs.BUILD_ID }}
          context: ./web
          push: true

      - name: ğŸ”  Replace SHA tag for containers and Helm chart
        uses: cschleiden/replace-tokens@v1.1
        with:
          files: '["package/**/*.yaml"]'
        env:
          BUILD_ID: ${{ steps.prep.outputs.BUILD_ID }}

      - name: ğŸ”  Lint and validate
        run: |
          helm template ./package  
          helm lint ./package

      - name: ğŸ—  Save helm chart to local registry
        run: |
          helm package ./package

      - name: ğŸš€  Publish chart to registry
        env:
          HELM_EXPERIMENTAL_OCI: 1
        run: |
          helm push open-arabic-helm*.tgz oci://registry.digitalocean.com/openarabic
